### ISSUE TITLE
Update press releases

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etcentral#111]
The are shown [here](http://www.et-model.com/press_releases)

**Comment by mariatsagkaraki** [comment]
Assigning @Susanaa

**Comment by ChaelKruip** [comment]
@Susanaa what is the status of this issues?

**Comment by AlexanderWirtz** [comment]
I think we should remove the press releases entirely, now that our company website contains most of the relevant information. What do you think @DorinevanderVlies ?

**Comment by AlexanderWirtz** [comment]
In general it couldn't hurt refer as much as possible to the professional website or quintel.com
