### ISSUE TITLE
Let's add Berenschot to the Partners section (I suppose non-paying for now)

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etcentral#113]
@dennisschoenmakers I believe you wanted to assign this to Thomas Wilkinson.

**Comment by jorisberkhout** [comment]
Could this be done with some priority, @dennisschoenmakers ? John wants to add Berenschot as well.

**Comment by grdw** [comment]
Is this still relevant today? If so, please do tell. The only thing I need are 

- A logo of Berenschot 
- Text about Berenschot in both Dutch 
- .. and English.

**Comment by AlexanderWirtz** [comment]
Let's start by adding their logo and name in the middel column (non-paying). The content I will ask for. with some priority please.

**Comment by AlexanderWirtz** [comment]
The Ecofys and CE Delft pages also have no text. Not a showstopper therefore.
