### ISSUE TITLE
Duplicate entry for SER fact checker press release link

### ISSUE THREAD

**Issue by Susanaa** [quintel/etcentral#121]
This press release is featured twice on our website. Could this be because there are two YML files containing this info?

1. One is [here](https://github.com/quintel/etcentral/blob/master/config/pressreleases/factchecker_energie_aflevering_1.yml)
2. and the other is [this one](https://github.com/quintel/etcentral/blob/master/config/pressreleases/ser_factchecker_1.yml)

@dennisschoenmakers please weigh in if you think you know what the problem is.

**Comment by twilkinson573** [comment]
Yeah that looks like the problem - nice catch! I'll remove one now.

**Comment by twilkinson573** [comment]
Fixed with 646999ef9e56eca3fd859c92de73d6415c285434
