### ISSUE TITLE
RLI scenarios should be redirected to beta now, later to production

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etcentral#122]
The following links should redirect currently to the next beta scenarios:

1. http://energietransitiemodel.nl/ser-scenario-2023 => http://beta.pro.et-model.com/scenarios/193349
2. http://energietransitiemodel.nl/80%-co2-reductiescenario-2050 => http://beta.pro.et-model.com/scenarios/423879
3. http://energietransitiemodel.nl/95%-co2-reductiescenario-2050 => http://beta.pro.et-model.com/scenarios/423882

I guess we can simply use:

```ruby
match "/name" => redirect {"http://beta.pro.et-model.com/scenarios/blah"}
```

in `config/routes.rb`

As requested by @AlexanderWirtz. 

Assigning @twilkinson573. Please put this in a Pull Request, including @jorisberkhout due to the deployment restrictions.

**Comment by AlexanderWirtz** [comment]
This has some priority

**Comment by dennisschoenmakers** [comment]
> This has some priority

**Comment by AlexanderWirtz** [comment]
Indeed, I was trying to use a British-type understatement. :smile:

**Comment by twilkinson573** [comment]
I agree `routes.rb` is the simplest way to do this.

@AlexanderWirtz the `%` (percent) character has a special meaning in URLs, so typing [http://energietransitiemodel.nl/80%-co2-reductiescenario-2050]() into Chrome would result in a broken link.

Would either of these be acceptable?

[http://energietransitiemodel.nl/80-co2-reductiescenario-2050]()
[http://energietransitiemodel.nl/80-percent-co2-reductiescenario-2050]()

**Comment by AlexanderWirtz** [comment]
yes it would @twilkinson573
