### ISSUE TITLE
ETMoses should be incorporated in the overview page

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etcentral#124]
![energy_transition_model](https://cloud.githubusercontent.com/assets/1303760/9932107/77395da8-5d41-11e5-92c8-701586d1ac63.png)

Also, ETMoses should be accessible from the applications menu. 
The energy mixer should still be approachable from the applications menu.

**Comment by dennisschoenmakers** [comment]
I think we also need fresh ideas on the captions below the apps: (5 minutes/30 minutes) etc. Perhaps just skip them and jump to the description immediately?

**Comment by ChaelKruip** [comment]
> Perhaps just skip them and jump to the description immediately?

I think that makes most sense. Less is more!

**Comment by jorisberkhout** [comment]
Adding milestone 'Deploy September 2015'

**Comment by ChaelKruip** [comment]
@dennisschoenmakers can we close this?

**Comment by dennisschoenmakers** [comment]
Fixed with #126
