### ISSUE TITLE
Update team members on http://et-model.com

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etcentral#125]
- [ ] Add Gerard and Georgia
- [ ] Remove Maria

<img width="1386" alt="screen shot 2015-09-28 at 11 52 29" src="https://cloud.githubusercontent.com/assets/4669028/10132652/e1d20c02-65d7-11e5-9180-4c1b232c1840.png">

Related to https://github.com/quintel/quintel.com/issues/47.

**Comment by jorisberkhout** [comment]
Assigning @dennisschoenmakers . Please re-assign if necessary.

**Comment by ChaelKruip** [comment]
@dennisschoenmakers what is the status of this?

**Comment by dennisschoenmakers** [comment]
Fixed with quintel/etcentral#126. I think it is better when we list people on quintel.com in stead of et-model.com
