### ISSUE TITLE
On beta, the link to the dutch ETM is broken

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etcentral#127]
<img width="1155" alt="404_not_found" src="https://cloud.githubusercontent.com/assets/1303760/10635237/82f9bcf2-77f7-11e5-94b1-ada833c09733.png">

**Comment by dennisschoenmakers** [comment]
Fixed it with a DNS adjustment, and https://github.com/quintel/ansible/commit/acce3ef7e2c386b2d78cc51bd4dd159f7571fb21

**Comment by dennisschoenmakers** [comment]
In the end I still like to 'fix' this: #93
