### ISSUE TITLE
Known issues page has to be updated (in better English than this issue contains)

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etcentral#128]
- [x] The fact that efficiencies for hydrogen are implemented but not for refining crude_oil into specific carriers
- [x] No investment costs for cars (but added investment for EV)
- [x] The ETM does not take energy flows into account that only pass through the country but instead calculates with net flows
- [x] The mix of exported electricity is the mix of domestic production (so even if wind produces the peaks, coal electricity is exported as well)

**Comment by jorisberkhout** [comment]
The first two issues in your list are on @RobTerwel 's and my radar. We will add them before the February deploy.

**Comment by RobTerwel** [comment]
In addition:
- [ ] LNG and hydrogen are not included in the employment calculation.

**Comment by jorisberkhout** [comment]
Given that all boxes above have been ticked, closing this issue.
