### ISSUE TITLE
http://beta.energytransitionmodel.com/ gives a 404 error

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etcentral#130]
As pointed out by John, all pages starting with http://beta.energytransitionmodel.com/ give a 404 error. http://beta.pro.energytransitionmodel.com/ does work.

**Comment by jorisberkhout** [comment]
Re-opened as http://beta.energytransitionmodel.com/ still gives a 404.

**Comment by dennisschoenmakers** [comment]
Issue lies with ansible: https://github.com/quintel/ansible/issues/22.

**Comment by dennisschoenmakers** [comment]
Manual restart of nginx fixed the issues. New ticket: quintel/ansible#24
