### ISSUE TITLE
Redirect do not work on live server?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etcentral#134]
At least http://energytransitionmodel.com/iabr/routekaartscenario-2035 does not work. including @AlexanderWirtz

**Comment by AlexanderWirtz** [comment]
same for `/iabr/routekaartscenario-2035` and `/iabr/routekaartscenario-2025` 

Note that the `/rli/ser-scenario-2023` and other Rli scenarios do get redirected correctly.

**Comment by grdw** [comment]
Turns out that this is not deployed yet to prodcution. Working on it.

**Comment by grdw** [comment]
It seems to be working now! :+1:

If you could try it out. If it doesn't work it could be that there's some browser cache

Output of curl:

````shell
$ curl -I "http://energytransitionmodel.com/iabr/routekaartscenario-2035"
HTTP/1.1 301 Moved Permanently
Server: nginx/1.6.3
Date: Tue, 16 Feb 2016 09:50:36 GMT
Content-Type: text/html
Content-Length: 106
Connection: keep-alive
Status: 301 Moved Permanently
Location: http://pro.et-model.com/scenarios/277819
X-UA-Compatible: IE=Edge,chrome=1
Cache-Control: no-cache
X-Request-Id: 7ad75ae4964a4114a639f4b30c852b96
X-Runtime: 0.001572
X-Rack-Cache: miss
````

**Comment by AlexanderWirtz** [comment]
Thanks!
