### ISSUE TITLE
Build currently broken

### ISSUE THREAD

**Issue by grdw** [quintel/etcentral#137]
![screen shot 2016-02-29 at 11 28 01 am](https://cloud.githubusercontent.com/assets/2676542/13391931/8bbf0594-ded7-11e5-9043-6e8f9139cfaa.png)

Some more information. The specs are failing because the redirects are literally tested. Fix the spec or in this case I might argue to not even keep the spec, because testing if "Rails can redirect" is a little bit outside of the scope of the application.

**Comment by ChaelKruip** [comment]
Fixed with https://github.com/quintel/etcentral/commit/ffaf4f30e32a428d10e5b3fb5d78a2ba939de80e
