### ISSUE TITLE
Add ETMobile to home page

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etcentral#151]

**Comment by dennisschoenmakers** [comment]
Also, it would make sense to put this option as first on mobile devices (i.e. when the screen width is small).

**Comment by antw** [comment]
A first pass of this is available on the `etmobile` branch. I think it could still use a bit more work before merging.

![screen shot 2017-02-10 at 20 13 34](https://cloud.githubusercontent.com/assets/4383/22842584/994b3568-efcd-11e6-864e-fd8169d0970e.png)

**Comment by dennisschoenmakers** [comment]
![image](https://cloud.githubusercontent.com/assets/104830/22845397/ac785e58-efe2-11e6-9378-cce04f914402.png)
