### ISSUE TITLE
Add Stichting Sanegeest to the partner list

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etcentral#165]
Stichting Sanegeest funded the addition of synthetic kerosene production to the ETM and would like to be included on the website. They do not have a logo, so I suggest to simply add their name and a link to their website (http://www.sanegeest.nl/) in the following places:

- [x] ETCentral (under 'Partners who share knowledge and support the ETM both financially and in kind')
- [x] ETModel (in the footer)
- [x] quintel.com

Could you make this happen, @grdw?

**Comment by grdw** [comment]
> [..] Partners who share knowledge and support the ETM both financially and in kind
>  ETModel (in the footer)

This can't _both_ be done at the same time. Currently only 'primary' partners are in the footer of the ETM (on the right). The left side remains frozen on 'GasTerra'. Do we want to change that, becuase of this issue?

---

In a broader sense (and not to sound really sour): I don't like how much space the footer is currently taking for the partners. My gut feeling tells me that it's also a little redundant considering the page on ETCentral + the animation from one partner to the next feels a little outdated. I'd suggest to remove the footer in it's entirity, but that's just my 10 cents.

**Comment by ChaelKruip** [comment]
> This can't both be done at the same time. Currently only 'primary' partners are in the footer of the ETM (on the right)

What are 'primary' partners other then "Partners who share knowledge and support the ETM both financially and in kind"?

> I'd suggest to remove the footer in it's entirity, but that's just my 10 cents.

I expect that would not sit well with the people who actually paid for the ETM over the years. I suggest we keep the footer. I am not opposed to any ideas to make it look less outdated though 😄

**Comment by grdw** [comment]
Merging PR https://github.com/quintel/etcentral/pull/167 will mean a couple of things

1. The partner will be visible on ETCentral in the left-most column
2. It will be featured in the footer of ETModel
3. It will have 2 pages (one for English and one for Dutch) which now only feature a link to their website (if it needs more content, please specify).

Merging PR: https://github.com/quintel/quintel.com/pull/109 will add it to the quintel website.

**Comment by jorisberkhout** [comment]
@grdw , Stichting Sanegeest now has a logo, see below. Could you add that to the existing PR?

![logo-f1](https://user-images.githubusercontent.com/4669028/35854182-fa9be9c4-0b2f-11e8-9613-a6fc4f154a99.jpg)
