### ISSUE TITLE
Add TNO to partners (paying)

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etcentral#174]
https://energytransitionmodel.com/partners

**Comment by redekok** [comment]
@ChaelKruip, I've added the en and nl markdown files for TNO (who is responsible for writing texts to display on the TNO partner page?) and I've listed TNO in the config/partners.yml file. I'm not sure how to add the logo image though. I think we need the S3 helper module for that? Could you help me out next week?

**Comment by redekok** [comment]
Resolved by https://github.com/quintel/etcentral/commit/6bb38c37cbb64856988eeb96d8307d6320d36959. Closing this issue.
