### ISSUE TITLE
Let's remove the 'Known issues' page

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etcentral#186]
I am pretty sure this hasn't been updated in a couple of years and I just don't like it.
https://energytransitionmodel.com/known_issues

This would imply we also remove this page: https://energytransitionmodel.com/quality_control 

@ChaelKruip re-assign at will

**Comment by AlexanderWirtz** [comment]
In fact, let's get rid of the whole information Tab

**Comment by noracato** [comment]
Closed with f698c98
