### ISSUE TITLE
the 'Watt Nu!?' link on energytransitionmode.com does not work. Domain name already registered

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etcentral#199]
This link:
http://wattnu.nl/

![image](https://user-images.githubusercontent.com/308563/86005495-063d9480-ba15-11ea-9683-b011a1f27e02.png)

re-assign as you see fit

**Comment by noracato** [comment]
For now I'll remove the link. But we should investigate what happened and if we want to reinstate the website
